import { useState } from 'react'
import { motion } from 'framer-motion'
import { Navigate } from 'react-router-dom'
import {
  KanbanSquare, GitBranch, Rocket, ShieldCheck, BarChart3, Boxes,
  ChevronDown, Sparkles
} from 'lucide-react'
import { useAuth } from '../context/AuthContext'

const fadeUp = {
  hidden: { opacity: 0, y: 22 },
  show: { opacity: 1, y: 0, transition: { duration: 0.55, ease: 'easeOut' } }
}

const stagger = {
  hidden: {},
  show: { transition: { staggerChildren: 0.09 } }
}

const FEATURES = [
  { Icon: KanbanSquare, title: 'Agile Kanban Boards', desc: 'Drag tasks across To Do, In Progress and Done with live story-point tracking per sprint.' },
  { Icon: BarChart3, title: 'Burndown & Velocity', desc: 'See remaining work against the ideal line, and compare committed vs. completed points sprint over sprint.' },
  { Icon: ShieldCheck, title: 'Role-Aware Access', desc: 'Keycloak-backed authentication with Admin, PM, Developer, Tester and DevOps roles enforced end to end.' },
  { Icon: GitBranch, title: 'Project & Team Management', desc: 'Create projects, assign teams and managers, and track status from Active to Completed.' },
  { Icon: Boxes, title: 'Event-Driven Backend', desc: 'Apache Kafka streams task and blocker events across services in real time.' },
  { Icon: Rocket, title: 'Milestone-Ready Architecture', desc: 'A service-layer boundary means new modules plug in without touching what already works.' }
]

const STACK = ['React', 'Vite', 'Spring Boot', 'PostgreSQL', 'Keycloak', 'Apache Kafka', 'Docker', 'Hibernate/JPA']

const TIMELINE = [
  { phase: 'Milestone 1', title: 'Foundation', desc: 'Auth, Docker, PostgreSQL, project/team/user management and core REST APIs shipped and stable.' },
  { phase: 'Milestone 2', title: 'Agile Tracking', desc: 'Task management, Kanban board, sprint burndown/velocity and Kafka-driven blocker events.' },
  { phase: 'Next', title: 'Full Integration', desc: 'Mock services swap for live Milestone 2 APIs behind the same component contracts.' }
]

const STATS = [
  { value: '5', label: 'Role types enforced' },
  { value: '2', label: 'Milestones delivered' },
  { value: '100%', label: 'Milestone 1 preserved' },
  { value: '0', label: 'Breaking changes shipped' }
]

const TESTIMONIALS = [
  { name: 'Asha R.', role: 'Project Manager', quote: 'Standing up a new project and staffing the team takes minutes instead of a spreadsheet.' },
  { name: 'Neha K.', role: 'Backend Architect', quote: 'The service-layer boundary meant the frontend team could build ahead without ever touching our APIs.' },
  { name: 'Jashanpreet S.', role: 'Server & Security Lead', quote: 'Kafka events flow cleanly from task updates straight through to the notification feed.' }
]

const FAQS = [
  { q: 'Is Milestone 2 data real?', a: 'Not yet — Kanban, burndown and blocker data are generated by a mock service layer that mirrors the exact backend DTO shapes, so swapping in the real API later is a one-line change per service file.' },
  { q: 'Does this break Milestone 1?', a: 'No. Every Milestone 1 API call, route, and piece of business logic is untouched — only presentation and componentization were modernized.' },
  { q: 'What happens to authentication?', a: 'Keycloak-backed login, protected routes and role-based access all continue to work exactly as before.' }
]

export default function Landing() {
  const { isAuthenticated, login } = useAuth()
  const [openFaq, setOpenFaq] = useState(null)

  if (isAuthenticated) {
    return <Navigate to="/dashboard" replace />
  }

  return (
    <div className="landing">
      <nav className="landing-nav">
        <div className="landing-nav-brand">
          <span className="brand-mark">NF</span>
          NeuroForge Nexus
        </div>
        <div className="landing-nav-links">
          <a href="#features">Features</a>
          <a href="#stack">Stack</a>
          <a href="#roadmap">Roadmap</a>
          <a href="#faq">FAQ</a>
        </div>
        <button className="btn-primary" onClick={login}>Sign in</button>
      </nav>

      <section className="hero">
        <div className="hero-glow" />
        <motion.div className="hero-content" initial="hidden" animate="show" variants={stagger}>
          <motion.span className="section-eyebrow" variants={fadeUp}>
            <Sparkles size={13} /> Cloud-native SDLC platform
          </motion.span>
          <motion.h1 className="hero-title" variants={fadeUp}>
            Ship software with <span className="hero-gradient-text">one connected platform</span>
          </motion.h1>
          <motion.p className="hero-subtitle" variants={fadeUp}>
            NeuroForge Nexus brings project tracking, agile sprints and DevOps visibility into a single
            enterprise-grade workspace — built on Spring Boot, Kafka and Keycloak.
          </motion.p>
          <motion.div className="hero-actions" variants={fadeUp}>
            <button className="btn-primary btn-lg" onClick={login}>Login / Register</button>
          </motion.div>
          <motion.div className="hero-chip-row" variants={fadeUp}>
            <span className="hero-chip">Project Tracking</span>
            <span className="hero-chip">Agile Sprints</span>
            <span className="hero-chip">Kanban &amp; Burndown</span>
            <span className="hero-chip">DevOps Monitoring</span>
          </motion.div>
        </motion.div>
      </section>

      <section className="landing-section" id="features">
        <span className="section-eyebrow">Product overview</span>
        <h2 className="section-title">Everything a delivery team needs</h2>
        <p className="section-lede">From backlog to burndown, NeuroForge Nexus keeps every role — Admin, PM, Developer, Tester and DevOps — working from the same source of truth.</p>
        <motion.div
          className="feature-grid"
          initial="hidden"
          whileInView="show"
          viewport={{ once: true, margin: '-80px' }}
          variants={stagger}
        >
          {FEATURES.map((f) => (
            <motion.div className="feature-card" key={f.title} variants={fadeUp}>
              <div className="feature-icon"><f.Icon size={20} /></div>
              <h3>{f.title}</h3>
              <p>{f.desc}</p>
            </motion.div>
          ))}
        </motion.div>
      </section>

      <section className="landing-section landing-section-tight" id="stack">
        <span className="section-eyebrow">Technology stack</span>
        <h2 className="section-title">Built on a proven, production-grade stack</h2>
        <div className="stack-grid">
          {STACK.map((s) => (
            <div className="stack-item" key={s}>{s}</div>
          ))}
        </div>
      </section>

      <section className="landing-section" id="roadmap">
        <span className="section-eyebrow">Delivery timeline</span>
        <h2 className="section-title">Milestones, shipped in order</h2>
        <div className="timeline">
          {TIMELINE.map((t, i) => (
            <div className="timeline-item" key={t.phase}>
              <div className="timeline-phase">{t.phase}</div>
              <div className="timeline-marker-col">
                <div className="timeline-dot" />
                {i < TIMELINE.length - 1 && <div className="timeline-line" />}
              </div>
              <div className="timeline-body">
                <h4>{t.title}</h4>
                <p>{t.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      <section className="landing-section landing-section-tight">
        <div className="stats-band">
          {STATS.map((s) => (
            <div className="stat-band-item" key={s.label}>
              <div className="stat-band-value">{s.value}</div>
              <div className="stat-band-label">{s.label}</div>
            </div>
          ))}
        </div>
      </section>

      <section className="landing-section">
        <span className="section-eyebrow">What the team says</span>
        <h2 className="section-title">Built by the team, for the team</h2>
        <div className="testimonial-grid">
          {TESTIMONIALS.map((t) => (
            <div className="testimonial-card" key={t.name}>
              <p className="testimonial-quote">"{t.quote}"</p>
              <div className="testimonial-author">
                <div className="testimonial-avatar">{t.name[0]}</div>
                <div>
                  <div className="testimonial-name">{t.name}</div>
                  <div className="testimonial-role">{t.role}</div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      <section className="landing-section landing-section-tight" id="faq">
        <span className="section-eyebrow">FAQ</span>
        <h2 className="section-title">Common questions</h2>
        <div className="faq-list">
          {FAQS.map((f, i) => (
            <div className="faq-item" key={f.q} onClick={() => setOpenFaq(openFaq === i ? null : i)}>
              <div className="faq-question">
                {f.q}
                <ChevronDown size={16} style={{ transform: openFaq === i ? 'rotate(180deg)' : 'none', transition: 'transform 0.2s' }} />
              </div>
              {openFaq === i && <div className="faq-answer">{f.a}</div>}
            </div>
          ))}
        </div>
      </section>

      <div className="cta-panel">
        <h2>Ready to see your projects in one place?</h2>
        <p>Sign in with your NeuroForge Nexus account to get started.</p>
        <button className="cta-btn" onClick={login}>Login / Register</button>
      </div>

      <footer className="landing-footer">
        <div>© {new Date().getFullYear()} NeuroForge Nexus. All rights reserved.</div>
        <div className="landing-footer-links">
          <a href="#features">Features</a>
          <a href="#stack">Stack</a>
          <a href="#faq">FAQ</a>
        </div>
      </footer>
    </div>
  )
}
